var buttonColours = ["red", "blue", "green", "yellow"]; // Color options for the game

var gamePattern = []; // Sequence of colors generated by the game
var userClickedPattern = []; // Sequence of colors clicked by the user

var started = false; // Game status
var level = 0; // Current level

$(document).keypress(function () {
  // Start game on key press
  if (!started) {
    $("#level-title").text("Level " + level);
    nextSequence(); // Generate the next sequence
    started = true; // Set game as started
  }
});

$(".btn").click(function () {
  // Handle button clicks
  var userChosenColour = $(this).attr("id"); // Get clicked color
  userClickedPattern.push(userChosenColour); // Add to user's sequence

  playSound(userChosenColour); // Play the corresponding sound
  animatePress(userChosenColour); // Animate button press

  checkAnswer(userClickedPattern.length - 1); // Check user's answer
});

function checkAnswer(currentLevel) {
  // Check user's input against game sequence
  if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(function () {
        nextSequence(); // Move to next sequence after delay
      }, 1000);
    }
  } else {
    playSound("wrong"); // Play wrong sound
    $("body").addClass("game-over"); // Add game over class
    $("#level-title").text("Game Over, Press Any Key to Restart");

    setTimeout(function () {
      $("body").removeClass("game-over"); // Remove game over class
    }, 200);

    startOver(); // Reset the game
  }
}

function nextSequence() {
  // Generate next color sequence
  userClickedPattern = []; // Reset user's sequence
  level++; // Increase level
  $("#level-title").text("Level " + level);
  var randomNumber = Math.floor(Math.random() * 4); // Get random number
  var randomChosenColour = buttonColours[randomNumber]; // Choose random color
  gamePattern.push(randomChosenColour); // Add to game sequence

  $("#" + randomChosenColour)
    .fadeIn(100) // Animate button
    .fadeOut(100)
    .fadeIn(100);
  playSound(randomChosenColour); // Play sound for chosen color
}

function animatePress(currentColor) {
  // Animate button press
  $("#" + currentColor).addClass("pressed");
  setTimeout(function () {
    $("#" + currentColor).removeClass("pressed"); // Remove animation class
  }, 100);
}

function playSound(name) {
  // Play sound based on color name
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function startOver() {
  // Reset game variables
  level = 0;
  gamePattern = [];
  started = false; // Mark game as not started
}
